### ISSUE TITLE
Webpack warnings

### ISSUE THREAD

**Issue by eoger** [rkatic/p#15] opened 2015-07-02 22:32 UTC
I get warnings when using p in a Webpack project:

> WARNING in ./bower_components/p/p.js
Critical dependencies:
240:30-37 require function is used in a way in which dependencies cannot be statically extracted
 @ ./bower_components/p/p.js 240:30-37

Looks like the culprit is [that line](https://github.com/rkatic/p/blob/master/p.js#L240), webpack doesn't seem to like the comma operator (what is it used for in that case?).

**Comment by rkatic** [comment] 2015-07-03 04:43
Duplicate of #12.

**Closed by rkatic** 2015-07-03 04:43 UTC
